/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import tpfinal.Produto;

/**
 *
 * @author Eric
 */
public class verificaEstoque extends javax.swing.JFrame {

    static ArrayList<modifProduto> list = new ArrayList<>();
    /**
     * Creates new form verificaEstoque
     */
    public verificaEstoque() {
        initComponents();
        addRowToJTable();
        populateComboBox();
    }
    
    public class modifProduto{
        public Produto prodz;
        public int quantidade;
        
        public modifProduto(Produto prod,  int quantidade)
        {
            this.prodz  = prod;
            //vem do BD
            this.quantidade = quantidade;
        }
    }
    
// create a list of users
    public ArrayList listaEsgotados()
    {
        ArrayList<modifProduto> list = new ArrayList<>();
        
//        
//        APOS IMPLEMENTAR BANCO DE DADOS
        

        /* SIZE OF PRODUTOS ESGOTADOS*/
        modifProduto prod[] = new modifProduto[10];
        for(int i = 0; i < 10; i++){
            
            //prod[i]= new Produto(getCodigo, getName, getQuant, getPreco);
            Produto produtinho = new Produto(i, "Produto "+i, "Modelo "+i, "Fabricante "+i);
            prod[i] = new modifProduto(produtinho, i*20);
            list.add(prod[i]);
        }
        return list;
    }
    
// added rows from arraylist to jtable
    public void addRowToJTable()
    {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        list = listaEsgotados();
        Object rowData[] = new Object[3];
        
        for(int i = 0; i < list.size(); i++)
        {
            rowData[0] = list.get(i).prodz.getCodigo();
            rowData[1] = list.get(i).prodz.getDescricao();
            rowData[2] = list.get(i).quantidade;
            model.addRow(rowData);
        }
                
    }
         
    public void populateComboBox(){ 
        
        ArrayList<modifProduto> list = listaEsgotados();
        /* SIZE OF PRODUTOS ESGOTADOS*/
        String[] produtos = new String[10];   
        
        /* SIZE OF PRODUTOS ESGOTADOS*/
        for(int i = 0; i < 10; i++) {
                produtos[i] = list.get(i).prodz.getDescricao();
        }       
        
        DefaultComboBoxModel md = new DefaultComboBoxModel(produtos);
        jComboBox1.setModel(md);
    }


    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        subtitulo = new javax.swing.JLabel();
        botVolta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        fazerRequisicao = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Estoque - Supermercados do Tião");

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Verificação de Estoque");

        subtitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo.setText("Abaixo encontra-se a lista de produtos que estão em falta:");

        botVolta.setText("Voltar");
        botVolta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVoltaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Qtd. em Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fazerRequisicao.setText("Fazer Requisição");
        fazerRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazerRequisicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subtitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                    .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botVolta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fazerRequisicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fazerRequisicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botVolta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void botVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVoltaActionPerformed
        mainMenu volta = new mainMenu();
        volta.setVisible(true);
        dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_botVoltaActionPerformed

    private void fazerRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazerRequisicaoActionPerformed
        String produto = (String)jComboBox1.getSelectedItem();
        
        /* SIZE OF PRODUTOS ESGOTADOS*/
        for (int i = 0; i < 10; i++){
            if (produto.equals(list.get(i).prodz.getDescricao())){
                formRequisicao requis;
                requis = new formRequisicao(list.get(i).prodz, 100-list.get(i).quantidade);
                requis.setVisible(true);
                dispose();
            }
        }  
    }//GEN-LAST:event_fazerRequisicaoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botVolta;
    private javax.swing.JButton fazerRequisicao;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
